theme: jekyll-theme-cayman

title: My Website
description: Welcome to my GitHub Pages site!
author: Ilyes Hamdi
baseurl: ""
url: "https://hamdilyes.github.io/"

header_pages:
  - index.md
  - blog.md

logo: /logo.png
